BenHoboCo/api/urls.py
from django.conf.urls import patterns, url, include

from .views import AuthorList, AuthorDetail
from .views import FriendList, FriendDetail, FriendCompare, FriendRequestView
from .views import ImageList, ImageDetail
from .views import PostList, AuthorPostList, PostDetail, PostsVisibileToAuthor

author_urls = patterns('',
    url(r'^$', AuthorList.as_view(), name="all_authors"),
    url(r'^(?P<guid>[-\w]+)/$', AuthorDetail.as_view(), name="specific_author"),
    url(r'^(?P<guid>[-\w]+)/posts/$', AuthorPostList.as_view(), name="specific_author_posts"),
)

post_urls = patterns('',
    url(r'^$', PostList.as_view(), name="posts" ),
    url(r'^(?P<guid>[-\w]+)/$', PostDetail.as_view(), name="post_detail"),
)

friends_urls = patterns('',
    url(r'^$',FriendList.as_view(), name="author_friends"),
    url(r'^(?P<guid_1>[-\w]+)/(?P<guid_2>[-\w]+)/$', FriendCompare.as_view(), name="compare_friends" ),
)

urlpatterns = patterns('',
    url(r'^authors/',include(author_urls)),
    url(r'^posts/',include(post_urls)),
    url(r'^my_posts/$', PostsVisibileToAuthor.as_view(), name="my_posts"),
    url(r'^friends/',include(friends_urls)),
    url(r'^friendrequest/$', FriendRequestView.as_view(), name="friendrequest")
)

BenHoboCo/images/urls.py
from django.conf.urls import url, patterns
from authors.views import get_author_images
from .views import create_image, upload_image

urlpatterns = patterns('',
    url(r'^$', get_author_images, name="author_images"),
    url(r'^(?P<image_id>\d+)/$', get_author_images, name="author_images"),
    url(r'^create/$', create_image, name="create_image"),
    url(r'^upload/$', upload_image,name="upload_images"),
)

BenHoboCo/posts/urls.py
from django.conf.urls import url, patterns
from .views import posts, create_post, add_comment, delete_post
from authors.views import get_author_posts
from .views import CreatePost

urlpatterns = patterns('',
    url(r'^$', posts, name="posts"),
    url(r'^(?P<post_id>\d+)/delete/$', delete_post, name="delete_comment"),
    url(r'^author/(?P<author_guid>\d+)/$', get_author_posts, name="author_posts"),

    url(
        regex = r'^create/$',
        view = CreatePost.as_view(),
        name = "create_post"
    ),

    url(regex=r'^(?P<post_id>.*?)/comment/$', view=add_comment, name="add_comment"),
    url(r'^(?P<post_id>.*?)/$', posts, name="posts"),
)

BenHoboCo/social/urls.py
from django.conf.urls import patterns, url
from social import views, api_views

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),

    #Authentication stuff
    url(r'^register/$', views.user_register),
    url(r'^login/$', views.user_login),
    url(r'^logout/$', views.user_logout),
    url(r'^manageAccount/updateAuthor/$', views.user_update_author),
    url(r'^manageAccount/changePassword/$', views.user_change_password),
    url(r'^manageAccount/$', views.manage_account),
    url(r'^manageAccount/changeImage/$', views.upload_profile_image),

    #authors - All Authors
    #authors/author_name/ - Specific Author

    # #authors/author_name/friends - Specific Author Friends
    # #authors/author_name/friends/friend_name - Specific Authors specific Friend
    # url(r'^authors/$', views.get_all_authors, name="authors"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/$',views.get_author, name="author"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/friends/addFriend/$', views.add_friend, name="author_add_friend"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/friends/(?P<friend_guid>\w+)/delete/$',views.delete_friend, name="authors_delete_friend"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/friends/$',views.get_author_friends, name="authors_specific_friend"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/friends/(?P<friend_guid>\w+)/$',views.get_author_friends, name="authors_specific_friend"),

    # # Friends
    # url(r'^friends/$',views.friends, name="author_friends"),
    # url(r'^friends/search/$',views.search_friend, name="authors_search_friend"),

    #This should be changed to
    #images/author/author_name
    #images/author/author_name/image_id or #images/image_id
    # url(r'^images/$',views.get_author_images, name="author_images"),
    # url(r'^images/(?P<image_id>\d+)/$',views.get_author_images, name="author_images"),
    # url(r'^images/create/$',views.create_image, name="create_image"),
    # url(r'^images/upload/$', views.upload_image,name="upload_images"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/images/create',views.create_image, name="create_image"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/images/$',views.get_author_images, name="author_images"),
    # url(r'^authors/(?P<author_guid>[-\w]+)/images/(?P<image_id>\d+)/$',views.get_author_images, name="authors_specific_image"),    

    #posts - all posts
    #posts/post_id - specific post
    #posts/author/bensontrinh - specific posts from a person
    # url(r'^posts/$', views.posts, name="posts"),
    # url(r'^posts/create/$', views.create_post, name="create_post"),
    # url(r'^posts/(?P<post_id>\d+)/$', views.posts, name="posts"),
    # url(r'^posts/(?P<post_id>\d+)/comment/$', views.add_comment, name="posts"),
    # url(r'^posts/(?P<post_id>\d+)/delete/$', views.delete_post, name="posts"),
    # url(r'^posts/author/(?P<author_guid>[-\w]+)/$', views.get_author_posts, name="author_posts"),


    #API
    # url(r'^api/authors/$', api_views.get_authors, name="get_authors"),
    # url(r'^api/authors/(?P<author_guid>[-\w]+)/$', api_views.get_authors, name="get_authors"),
    # url(r'^api/authors/(?P<author_guid>[-\w]+)/posts/$', api_views.get_posts, name="api_get_posts"),
    # url(r'^api/authors/(?P<author_guid>[-\w]+)/posts/(?P<post_guid>[-\w]+)/$', api_views.get_posts, name="api_get_posts"),

    #POST a list of friends and returns a list of friends who the <author_guid> is friends with
    #url(r'^api/friends/(?P<author_guid>[-\w]+)/$', api_views.get_friends, name="friends"),

    #Compares the two provided friends and checks if they are friends
    # url(r'^api/friends/(?P<friend1_guid>[-\w]+)/(?P<friend2_guid>[-\w]+)/$', api_views.compare_friends, name="compare_friends"),
    
    #Friend request
    url(r'^api/friendrequest/$', api_views.friend_request, name="friend_request"),
)

BenHoboCo/authors/models.py
from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.fields import UUIDField

# Create your models here.
class Author(models.Model):

    #User already contains: username, password, first_name, last_name, email
    user = models.OneToOneField(User)

    image = models.ImageField( null = True, blank=True, upload_to="Images")
    host = models.URLField(max_length=256) #This specifies the authors host

    guid = UUIDField()

    github = models.CharField(max_length=30, default="")

    url = models.URLField(max_length=256) #This specifies the url of the authors page

    def __unicode__(self):
        return self.user.username

    def image_url(self):
        if self.image:
            return self.image.url
        else:
            return ""

    def get_full_name(self):
        return "%s %s" % ( self.user.first_name, self.user.last_name )

    def json(self):
        return dict (
            id = self.guid,
            host = self.host,
            displayname = self.get_full_name(),
            url = "%s/authors/%s" % (self.host, self.guid),
            github = self.github
        )

BenHoboCo/images/models.py
from django.db import models
from core.models import ACCESSIBILITY_TYPES
from authors.models import Author


class Image(models.Model):
    author = models.ForeignKey(Author, related_name="author")
    url = models.CharField(max_length=256)
    visibility = models.CharField( max_length=128, choices=ACCESSIBILITY_TYPES )
    image = models.ImageField( blank=True, upload_to="Images")

    def __unicode__(self):
        return self.url

    @property
    def base64( self ):
        try:
            img = open( self.image.path, "rb")
            data = img.read()
            return  "data:image/jpg;base64,%s" % data.encode('base64')
        except IOError as e:
            return "error"

BenHoboCo/posts/models.py
from django.db import models
from django_extensions.db.fields import UUIDField
from authors.models import Author
from datetime import datetime
from core.models import ACCESSIBILITY_TYPES

class Post(models.Model):
    author = models.ForeignKey(Author)

    title = models.CharField(max_length=256)
    source = models.URLField(max_length=256)
    origin = models.URLField(max_length=256)

    description = models.CharField(max_length=256)
    content_type = models.CharField(max_length=256)
    content = models.TextField()

    #We may want a separate model for this actually
    categories = models.TextField()

    #We find comments through the comment model.
    #No need for a comments field here

    pubDate = models.DateTimeField(default=datetime.now)
    visibility = models.CharField( max_length=128, choices=ACCESSIBILITY_TYPES )

    guid = UUIDField()

    def __unicode__(self):
        return "%s, %i" % (self.author.user.username, self.id)

class Comment(models.Model):
    author = models.ForeignKey(Author)
    pubDate = models.DateTimeField(default=datetime.now)
    post = models.ForeignKey(Post, related_name="comments")
    comment = models.TextField()

    guid = UUIDField()

    def __unicode__(self):
        return "%s posted a comment to Post %d" % ( self.author.user.username, self.post.id )

BenHoboCo/authors/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Author

class UserForm(forms.ModelForm):
    username = forms.CharField(help_text="Username", widget=forms.TextInput({ 'placeholder': "Enter Username", 'class':'form-control' }))
    email = forms.CharField(help_text="Email", widget=forms.TextInput({ 'placeholder': "Enter Email", 'class':'form-control' }))
    first_name = forms.CharField(help_text="First Name", widget=forms.TextInput({ 'placeholder': "Enter First Name", 'class':'form-control' }))
    last_name = forms.CharField(help_text="Last Name", widget=forms.TextInput({ 'placeholder': "Enter Last Name", 'class':'form-control' }))
    password = forms.CharField(help_text="Password", widget=forms.PasswordInput({ 'placeholder': "Enter Password", 'class':'form-control' }))

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')

class AuthorForm(forms.ModelForm):
    image = forms.ImageField(help_text="Profile Picture", required=False)

    class Meta:
        model = Author
        fields = ('image', 'github')

BenHoboCo/images/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

BenHoboCo/authors/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponseRedirect

from authors.forms import AuthorForm

from authors.models import Author
from posts.models import Post
from friends.models import Friend
from images.models import Image

from django.contrib.auth.models import User

# Create your views here.
@login_required
def get_all_authors(request):
    context = RequestContext( request )
    # We grab all the authors that aren't the currently logged in user.
    a = Author.objects.exclude(user=request.user)

    context_dict  = {'authors': a}
    return render_to_response('social/authors.html', context_dict, context )

#get specific author information
@login_required
def get_author(request, author_guid = None):
    context = RequestContext( request )

    try:
        u = User.objects.get(username=author_guid)
        a = Author.objects.get(user=u)
    except User.DoesNotExist:
        a = Author.objects.get(guid=author_guid)
        u = a.user

    if request.method == "GET":
        loggedInUser = Author.objects.get(user = request.user)
        #in my profile I want to see posts that are private to me
        #posts that are from my friends that are shared as "friends of friends"
        #posts that are shared to me by local_friends

        #posts that are shared to me by global_friends
        #posts that are shared to me by friends of friends

        #friends of author
        friends = Friend.objects.filter( author = Author.objects.get(user=request.user) )

        #Get the posts where the author is the user signed in
        # and also where the author is in the list of friends
        friend_names = [ friend.friend_name for friend in friends ]
        friend_guids = [ friend.friend_guid for friend in friends ]

        users = User.objects.filter(username__in=friend_names)

        authors = Author.objects.filter(user__in=users)

        #If the post is private, we won't show it.
        #If the post is friends_of_friends we will show it
        #If the post is local then the user will be registered. Since we are only polling
        #users that are registered and finding the authors that way, we will only
        #have local friends atm.


        # IN HERE WE ONLY WANT TO SEE THE FRIEND POSTS AND MY POSTS
        # WE ONLY SHOW ALL PUBLIC POSTS IN THE INDEX PAGE
        #First get all the posts that are public
        
        friends_as_authors = []
        friends_as_authors = [ Author.objects.get(guid=fn) for fn in friend_guids ]

        posts = Post.objects.all()

        public_posts = Post.objects.all().filter(visibility="PUBLIC").filter(author__in = friends_as_authors )

        #Visible to friends
        friend_posts = posts.filter(visibility="FRIENDS").filter(author__in = friends_as_authors )

        private_posts = posts.filter(visibility="PRIVATE").filter(author = request.user.author )

        posts = public_posts | friend_posts | private_posts 

        print posts

        images = Image.objects.filter(author=a)
        friend_guids.append(Author.objects.get(user=request.user).guid)

        context_dict = {'author':a, 'user_posts': posts, 'our_friends': friend_guids, 'user_images': images, 'logged_in_user' : loggedInUser}


        return render_to_response('social/profile.html', context_dict, context )
    elif request.method == "POST":
        if u.username == request.user.username:
            form = AuthorForm(request.POST, instance=a)
            form.save()
        return HttpResponseRedirect("/authors/%s/" % author_guid)


# Updates the Author information.
# Only accepts posts, and returns back to the management page.
@login_required
def user_update_author(request):
    context = RequestContext(request)

    u = request.user
    a = Author.objects.get(user = u)

    # Update the user account information.
    if request.method == "POST":
        newGithub = request.POST['gitHub']
        a.github = newGithub
        a.save()
        return render_to_response('social/manageProfile.html', {'author': a, 'user': u, 'github_success': True}, context)

    return render_to_response('social/manageProfile.html', {'author': a, 'user': u }, context)


def get_author_images(request, author_guid = None, image_id = None ):
    context = RequestContext( request )

    #get User object then find the Author object from it
    if author_guid is not None:
        a = Author.objects.get(guid=author_guid)
    else:
        a = Author.objects.get(user=request.user)

    context_dict = {}

    if image_id is not None:
        try:
            context_dict['image'] = Image.objects.get(id=image_id)
        except ObjectDoesNotExist:
            pass #do nothing for now

        return render_to_response('social/images.html', context_dict, context )

    context_dict['user_images'] = Image.objects.filter(author=a)

    #no content
    return render_to_response('social/images.html', context_dict, context )

def get_author_posts(request, author_guid ):
    context = RequestContext( request )

    #get User object then find the Author object from it
    a = Author.objects.get(guid=author_guid)
    context_dict = {}
    context_dict['author'] = a

    posts = Post.objects.filter(author=a)
    
    #First get all the posts that are public
    public_posts = posts.filter(visibility="PUBLIC")

    #Visible to friends
    current_user_friends = request.user.author.friends.all()
    friend_posts = posts.filter(visibility="FRIENDS").filter(author__in = current_user_friends )

    private_posts = posts.filter(visibility="PRIVATE").filter(author = request.user.author )

    posts = public_posts | friend_posts | private_posts 

    context_dict['user_posts'] = posts

    return render_to_response('social/posts.html', context_dict, context )

BenHoboCo/images/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db.models import Q
from django.http import HttpResponseRedirect

from images.forms import ImageUploadForm

from authors.models import Author
from images.models import Image

@login_required
def create_image(request, author_guid = None ):
    context = RequestContext(request)
    u = request.user
    a = Author.objects.get(user = u)

    context_dict = {'author': a, 'success': False }
    return render_to_response('social/createImage.html', context_dict, context)

@login_required
def upload_image(request):
    if request.method == "POST":
        context = RequestContext(request)
        auth = Author.objects.get(user=request.user)
        form = ImageUploadForm(request.POST, request.FILES)
        access = request.POST['access']
        if form.is_valid():
            url = "/media/Images/" + str(form.cleaned_data['image']) 
            image = Image(image=form.cleaned_data['image'],url=url, visibility=access, author=auth)
            image.save()
    return HttpResponseRedirect("/images/")

BenHoboCo/templates/social/addRemoteFriend.html
{% extends 'social/base.html' %}
{% block block_body %}
<div class="row">
	<div class="page-header">
		<h1>Add Friend</h1>
	</div>
</div>
<div class="row col-md-4 col-md-offset-3">
	<form method="POST" action="/authors/{{ user.username }}/friends/" role="form">
		{% csrf_token %}
		<!-- error messages for invalid post stuff here -->

		<div class="form-group">
			<label for="friendName" class="control-label">Friend Name</label>
			<input type="text" name="friend_name" value="{{friend_name}}" class="form-control" />
		</div>
		<div class="form-group">
			<label for="content" class="control-label">Location</label>
			<input type="text" name="friend_location" value="{{friend_location}}" class="form-control" /> 
		</div>
		<div class="form-group">
			<input type="submit" class="btn btn-primary" value="Add Friend"/>
			<a href="/authors/{{ author.user.username }}/friends" class="btn btn-default">Cancel</a>
		</div>
	</form>
</div>
{% endblock %}

BenHoboCo/templates/social/authors.html
{% extends 'social/base.html' %}
{% block block_body %}
<div class="row">
    {% if user_posts %}
    <ul>
        {% for p in user_posts %}
        <li> <p><b>Author:</b> {{ p.author.user.username }}  </p>
            <p><b>Content:</b> {{ p.content }}</p>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if authors %}
    <div class="page-header">
        <h1>Authors</h1>
        <p class="text-info"> Connect with your fellow <strong>believers</strong>!</p>
    </div>
    <div class="row">
        <div class="col-md-8">
          {% for a in authors %}
          <div class="media">
                <a class="pull-left" href="/authors/{{a.guid}}">
                  {% if a.image %}
                    <img class="media-object" style="width: 75%; height: auto" src="{{ a.image.url | urlencode }}"/>
                  {% else %}
                    <img class="media-object" src="/static/img/placeholder.png"/>
                  {% endif %}
                </a>
              <div class="media-body">
                  <h3 class="media-heading">{{ a.get_full_name }}  <small>({{a.user.username}})</small></h3>
                  <p>{{a.user.email}}</p>
              </div>
          </div>
          {% endfor %}
        </div>
    </div>
    {% endif %}

  {% if author %}
  <h1>{{ author.user.username }}</h1>
  <p><b>Email:</b> {{ author.user.email }}</p>

  {% endif %}

  {% if post %}
  <p><b>Author:</b> {{ post.author.user.username }}</p>
  <p><b>Content: </b> {{ post.content }} </p>
  {% endif %}
</div>
{% endblock %}

BenHoboCo/templates/social/createImage.html
{% extends 'social/base.html' %}
{% block block_body %}

<div class="row">
	<div class="page-header">
		<h1>Upload an Image</h1>
	</div>
</div>

{% if success %}
<div class="alert alert-success">
	Image uploaded successfully!
</div>
{% endif %}
<div class="row col-md-9 col-md-offset-1">

<div class="form-group col-md-4">
<form action="/images/upload/" method="post" enctype="multipart/form-data">
 {% csrf_token %}

        <label for="fil_upload" class="control-label">File Upload</label>
        <input id="id_image" type="file" name="image">         
        <br>        
        <label for="access" class="control-label">Access Control</label>
                <select name="access" class="form-control">
                    <option value="PUBLIC">Public</option>
                    <option value="PRIVATE">Private</option>
                    <option value="private_to_another">Private To another author</option>
                    <option value="SERVERONLY">Friends on this host</option>
                    <option value="FRIENDS">Friends</option>
                    <option value="FOAF">Friends of friends</option>
                </select>

                <br>
                <input type="submit" class="btn btn-primary" value="Upload Image">
</form>
</div> 
</div>


<script>
	function selectDefault(){
		document.getElementById("text_content").click();
	}
</script>
<body onload="selectDefault()">
	{% endblock %}

BenHoboCo/templates/social/friendSearch.html
{% extends 'social/base.html' %}
{% block block_body %}
<div class="row">
	<div class="page-header">
		<h1><a href="/friends/"><span class="glyphicon glyphicon-chevron-left"></span></a>  Find a Friend</h1>
	</div>
	<form class="form-horizontal" role="form" method="POST" action="/friends/search/">
		{% csrf_token %}
		{% if host_unselected %}
			<div class="alert alert-danger">
				<strong>Whoops!</strong> You forgot to specify a host.
				</div>
			<div class="form-group has-error">
		{% else %}
			<div class="form-group">
		{% endif %}
			<label for="friendSearch" class="col-sm-1 control-label">Search:</label>
			<div class="col-sm-2">
				<select class="form-control" name="host_name">
					<option>Select Host</option>
					{% for host in hosts %}
						<option>{{ host }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="col-sm-8">
				<input type="text" class="form-control" name="friend_name" placeholder="Enter a name"/>
			</div>
			<div class="col-sm-1">
				<button type="submit" class="btn btn-success">Search!</button>
			</div>
		</div>
	</form>
	<hr/>
	<div class="col-md-9 col-md-offset-1">
		{% for author in found_authors %}
			<div class="media">
				<div class="pull-left">
					{% if author.host == "127.0.0.1:8000" %}
						<a href="/authors/{{author.guid}}">
							<img class="media-object" src="/static/img/placeholder.png"/>
						</a>
					{% endif %}
				</div>
				<div class="media-body">
					<h3 class="media-heading">{{author.name}}</h3>
					<div class="col-md-6">
						<p>Host: {{author.host}}</p>
						<p>ID: {{author.guid}}</p>
					</div>
					<div class="col-md-6">
						<form method="POST" action="/authors/{{author.guid}}/friends/addFriend/">
							{% csrf_token %}
							<div class="form-group">
								<input type="hidden" name="friend_name" value="{{author.name}}"/>
								<input type="hidden" name="friend_guid" value="{{author.guid}}"/>
								<input type="hidden" name="friend_location" value="{{author.host}}"/>
								<input type="submit" id="addFriendButton" class="btn btn-success" class="form-control" value="Add Friend"/>
							</div>
						</form>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

BenHoboCo/templates/social/profile.html
{% extends 'social/base.html' %}
{% block block_body %}
<div class="row">
	{% if author.user == request.user %}
		<div class="alert alert-info alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Hey!</strong> This is what other people will see when they look at your profile.  To edit your profile, click on the "Manage Profile" link on the upper right hand corner!
		</div>
	{% endif %}
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<!-- <h1>{{ author.user.username }} <a href="" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Add Friend</a></h1> -->
				<h1>
					{{ author.get_full_name }} <small>({{author.user.username}})</small>
				</h1>
				<form method="POST" action="/authors/{{author.guid}}/friends/addFriend/">
					{% csrf_token %}
					
					{% if not author.guid in our_friends %}
					<input type="hidden" name="friend_name" value="{{logged_in_user.get_full_name}}"/>
					<input type="hidden" name="friend_guid" value="{{logged_in_user.guid}}"/>
					<input type="hidden" name="friend_location" value=""/>
					<input type="submit" value="Add Friend" class="btn btn-success"/>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-3 text-center">
				{% if author.image %}
					<img style="width: 75%; height: auto" src="{{ author.image.url | urlencode }}"/> 
				{% else %}
					<img src="/static/img/placeholder.png" class="img-thumbnail"/>
				{% endif %}
			</div>
			<div class="col-md-8">
				<p><strong>Email:</strong> {{author.user.email}}</p>
				<p><strong>ID:</strong> {{author.guid}}</p>
			</div>
		</div>
	</div>
	<hr/>
	<div class="row">
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h2 class="panel-title">Images</h2>
				</div>
			</div>
                	<div class="list-group">
                        {% if user_images  %}
                                <ul>
                                {% for i in user_images %}
                                    <li>
                                    <p><img width=auto height=150 src="{{ i.url | urlencode }}"/></p>
                                    </li>
                                {% endfor %}
                                </ul>
                         {% endif %}
                	</div>
		</div>

		<div class="col-md-6">
            {% if author.github %}
                <div class="row">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h2 class="panel-title">Github Activity</h2>
                        </div>
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading"> {{ author.user.first_name }}'s recent Github activity</h4>
                            <p class="list-group-item-text" id="github-content"></p>
                        </div>
                    </div>
                </div>
                <script>
                    $(document).ready(function(){
                        $.get("https://api.github.com/users/{{author.github}}/events", "json").done(function(data){
                            var events= 0;
                            for (d in data){
                                if (events < 3) {
                                    if (data[d]["type"] === "PushEvent"){
                                        var commitText = "a new commit";
                                        if (data[d].payload.size > 1) {
                                            commitText = data[d].payload.size + " new commits"
                                        }
                                        $("#github-content").append("<a href=\"http://github.com/"+data[d].actor.login+"\">" 
                                            +data[d].actor.login+"</a> pushed "+commitText+" to "+"<a href=\"http://github.com/"
                                            +data[d].repo.name+"\">"+data[d].repo.name+"</a><br/>");
                                        events++;
                                    }
                                    else if (data[d]["type"] === "ForkEvent"){
                                        $("#github-content").append("<a href=\"http://github.com/"+data[d].actor.login+"\">" 
                                            +data[d].actor.login+"</a> forked "+ "<a href=\"http://github.com/"
                                            +data[d].repo.name+"\">"+data[d].repo.name+"</a><br/>");
                                        events++;
                                    }
                                    else if (data[d]["type"] === "CommitCommentEvent"){
                                        $("#github-content").append("<a href=\"http://github.com/"+data[d].actor.login+"\">" 
                                            +data[d].actor.login+"</a> commented on a commit to "+ "<a href=\""
                                            +data[d].payload.comment.html_url+"\">"+data[d].repo.name+"</a><br/>");
                                        events++;
                                    }
                                    else if (data[d]["type"] === "PullRequestEvent"){
                                        $("#github-content").append("<a href=\"http://github.com/"+data[d].actor.login+"\">" 
                                            +data[d].actor.login+"</a> "+data[d].payload.action+" pull request #"
                                            +data[d].payload.number+" to <a href=\""+ data[d].payload.pull_request.html_url
                                            +"\">"+data[d].repo.name+"</a><br/>");
                                        events++;
                                    }
                                }
                            }
                        });
                    });
                </script>
            {% endif %}
            <div class="row">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h2 class="panel-title">Posts</h2>
                    </div>

                    <ul class="list-group">
                        {% for post in user_posts %}
                            <a href="/posts/{{post.id}}/" class="list-group-item">
                                <h4 class="list-group-item-heading"> {{ post.title }} <small> on {{ post.pubDate }} </small></h4>
                                <div class="well">
                                    <p class="list-group-item-text">{{ post.content | safe }}</p>
                                </div>
                                <p class="text-right">{{post.comment_set.all|length}} Comments</p>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
		</div>
	</div>
</div>

{% endblock %}